spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
jpa:
hibernate:
ddl-auto: update
show-sql: true
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000 # 1 hour